name: 🚀 Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    name: 🔍 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download deps
        run: npm ci

      - name: Format
        run: npm run format:ci
